version: '2.1'

services:
  dmd_project:
    image: dmd_project
    build: .
    volumes: 
      - .:/app:Z
    depends_on:
      - db
    ports:
      - 5000:5000
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: car_sharing_password
      POSTGRES_DB: car_sharing